//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Contract_ID { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<int> Contract_kind_ID { get; set; }
        public Nullable<System.DateTime> Contract_date { get; set; }
        public Nullable<int> Contract_no { get; set; }
        public Nullable<decimal> Contract_sum { get; set; }
        public string Payer_kind { get; set; }
    
        public virtual SContract_Kind SContract_Kind { get; set; }
        public virtual Student Student { get; set; }
    }
}
