//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Lesson_kind_ID { get; set; }
        public Nullable<int> Teach_plan_ID { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public Nullable<int> Hours { get; set; }
    
        public virtual SLesson_kind SLesson_kind { get; set; }
    }
}
