//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string Sex { get; set; }
        public string Birth_place { get; set; }
        public string Address { get; set; }
        public string Telephon { get; set; }
        public Nullable<int> Nation_ID { get; set; }
        public Nullable<int> Citizen_ID { get; set; }
        public Nullable<int> Social_ID { get; set; }
    }
}
