//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semester
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semester()
        {
            this.Teach_Plan = new HashSet<Teach_Plan>();
        }
    
        public int Semester_ID { get; set; }
        public Nullable<System.DateTime> Teach_begin_date { get; set; }
        public Nullable<System.DateTime> Teach_end_date { get; set; }
        public Nullable<System.DateTime> Session_begin_date { get; set; }
        public Nullable<System.DateTime> Session_end_date { get; set; }
        public Nullable<System.DateTime> Attest1_date { get; set; }
        public Nullable<System.DateTime> Attest2_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teach_Plan> Teach_Plan { get; set; }
    }
}
