//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLesson_kind
    {
        public int Lesson_kind_ID { get; set; }
        public string Lesson_kind_name { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
