//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teach_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teach_Plan()
        {
            this.Student_Marks = new HashSet<Student_Marks>();
        }
    
        public int Teach_plan_ID { get; set; }
        public Nullable<int> Semester_ID { get; set; }
        public Nullable<int> Group_ID { get; set; }
        public Nullable<int> Subject_ID { get; set; }
        public Nullable<int> Tester_ID { get; set; }
        public Nullable<int> Test_kind_ID { get; set; }
        public Nullable<System.DateTime> Test_date { get; set; }
        public Nullable<bool> Is_obligatory { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Marks> Student_Marks { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
