//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3_KIST_.net_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KIST_Lab3Entities : DbContext
    {
        public KIST_Lab3Entities()
            : base("name=KIST_Lab3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cafedra> Cafedras { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<SContract_Kind> SContract_Kind { get; set; }
        public virtual DbSet<SDiploma> SDiplomas { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<SLesson_kind> SLesson_kind { get; set; }
        public virtual DbSet<SMark> SMarks { get; set; }
        public virtual DbSet<Speciality> Specialities { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Group> Student_Group { get; set; }
        public virtual DbSet<Student_Marks> Student_Marks { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teach_Plan> Teach_Plan { get; set; }
    }
}
